apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 869823016797.dkr.ecr.us-east-1.amazonaws.com/prasanth-frontend:latest
          ports:
            - containerPort: 80
