apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer   # So it gets an external IP/ELB in AWS
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
